model:
    arch: nas-unet
data:
    dataset: pascal_voc
    train_split: train_aug
    split: val
    img_rows: 'same'
    img_cols: 'same'
searching:
    init_channels: 16
    depth: 3
    epoch: 400
    batch_size: 16
    report_freq: 20
    n_workers: 2
    alpha_begin: 10
    max_patience: 40
    gpu: True
    multi_gpus: False
    sharing_normal: False
    double_down_channel: False
    meta_node_num: 2
    grad_clip: 5
    train_portion: 0.5
    model_optimizer:
        name: 'adabound'
        lr: 1.0e-3
        weight_decay: 5.0e-4
    arch_optimizer:
        name: 'adam'
        lr: 3.0e-4
        weight_decay: 5.0e-3
    loss:
        name: 'cross_entropy'
        size_average: False
        aux_weight:
    resume:
training:
    geno_type: NASUNET
    init_channels: 64
    depth: 6
    epoch: 800
    batch_size: 1
    report_freq: 50
    n_workers: 2
    multi_gpus: False
    double_down_channel: True
    grad_clip: 3
    max_patience: 20
    model_optimizer:
        name: 'sgd'
        lr: 5.0e-2
        weight_decay: 1.0e-4
    loss:
        name: 'cross_entropy'
        aux: False
        aux_weight: 0.2
    backbone:
    lr_schedule:
        name: 'poly_lr'
        max_iter: 100
    resume:
